### ISSUE TITLE
./F/model_sm.F:144:23: Error: Symbol ‘alfas’ at (1) has no IMPLICIT type

### ISSUE THREAD

**Issue by benzahia** [HEPcodes/FormCalc#1]
I focus on beyond the Standard Model (SM) physic, I use FeynRules for generating FeynArts output, to make numerical evaluation with FormCalc at NLO;
When I use FeynArts output (generated by FeynRules) to "make" with FormCalc, I'm getting this error:

______________________________________________________________`
./F/model_sm.F:144:23: Error: Symbol ‘alfas’ at (1) has no IMPLICIT type
./F/model_sm.F:145:12: Error: Symbol ‘alfas2’ at (1) has no IMPLICIT type
./F/model_sm.F:146:8:

 #if MB_SCHEME != ONSHELL
        1
Error: Symbol ‘gs’ at (1) has no IMPLICIT type
./F/model_sm.F:146:20:

 #if MB_SCHEME != ONSHELL
                    1
Error: Symbol ‘pi’ at (1) has no IMPLICIT type
makefile:136: recipe for target 'run' failed
make: *** [run] Error 1
_______________________________________________________________`
Please, Is there any suggestion to do.
Thank you.

**Comment by misho104** [comment]
Please contact the author of FormCalc from http://www.feynarts.de/formcalc/ (the official URL).
